### PR TITLE
We ate bugs

### LINKED ISSUE #10: [graph-vis] Make the IoK prettier
CSS or something

### LINKED ISSUE #89: Re-organize sidebar
The presentation of the sidebar is not yet finalized, but the basic organization is complete.

Two mockups showing the desired re-organization:
| Light theme | Dark theme |
| -- | -- |
| image | image |

### LINKED ISSUE #122: [bug] merging with yourself
image

### LINKED ISSUE #127: [bug] layout is whack when importing

### PR DESCRIPTION
**Pull request by rianadon**
## Motivation

- Connecting nodes :tada: 
- New layout :confetti_ball: 
- Minor fixes :partying_face: 

## Related PRs or Issues

Fixes #127.
Fixes #122.

Some older ones as well
Fixes #89 
Fixes #10

### CODE REVIEW

**Review by rustielin — APPROVED** [review]
nice1!

File: v4/src/IokEdit.jsx [hunk 1]
```diff
@@ -77,27 +88,40 @@ class IokEdit extends Component {
...
+      if (prevNode !== null && id === prevNode.id) {
+        selectNode(null);
+        return;
       }
+      selectNode(id);
+      // extra below
+      const { secretCodeSign } = this.state;
+      this.setState({ secretCodeSign: [...secretCodeSign, id] }, () => {
+        // eslint-disable-next-line
+        if (JSON.stringify(this.statesecretCodeSign) === JSON.stringify(['04eaf9a2a65d37f254fab35f969da7b133cea2087e1be846ea2dc8ccbb0e2470',
```
Comment (rustielin) [inline v4/src/IokEdit.jsx:110]: what's this?

File: v4/src/layout.js [hunk 2]
```diff
@@ -0,0 +1,67 @@
+function TreeCircleLayout(options) {
```
Comment (rustielin) [inline v4/src/layout.js:1]: :o wow this is cool
